prog_ing_DostavaHrane/prog_ing_DostavaHrane/Controllers/HranasController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using prog_ing_DostavaHrane.Models.Context;

namespace prog_ing_DostavaHrane.Controllers
{
    public class HranasController : Controller
    {
        private readonly DostavaHraneP31ATigriciContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly UserManager<IdentityUser> _userManager;

        public HranasController(DostavaHraneP31ATigriciContext context, IHostingEnvironment hostingEnvironment, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            _userManager = userManager;
        }

        // GET: Hranas
        public async Task<IActionResult> Index()
        {
            var dostavaHraneP31ATigriciContext = _context.Hrana.Include(h => h.Restoran).Include(h => h.Tip);
            return View(await dostavaHraneP31ATigriciContext.ToListAsync());
        }
        [HttpPost]
        public ActionResult UvecajGlas(int? id)
        {
            var hrana = _context.Hrana.Where(p => p.Id == id).FirstOrDefault();
            if (hrana.Glasovi==null)
            {
                hrana.Glasovi = 0;
            }
            hrana.Glasovi++;
            _context.SaveChanges();
            return Json(hrana.Glasovi);
        }
        public ActionResult DodajJos(int? id)
        {
            var hrana = _context.Hrana.Where(p => p.Id == id).FirstOrDefault();
            hrana.Kolicina++;
            _context.SaveChanges();
            return Json(hrana.Kolicina);
        }
        public ActionResult MakniJos(int? id)
        {
            var hrana = _context.Hrana.Where(p => p.Id == id).FirstOrDefault();
            if (hrana.Kolicina>1)
            {
                hrana.Kolicina--;
                _context.SaveChanges();
            }
            return Json(hrana.Kolicina);
        }
        public async Task<IActionResult> HranaPoRestoranu(int id)
        {
            var dostavaHraneP31ATigriciContext = _context.Hrana.Include(h => h.Restoran).Include(h => h.Tip).Where(h=>h.RestoranId==id);
            return View(await dostavaHraneP31ATigriciContext.ToListAsync());
        }
        public async Task<IActionResult> HranaPoKategoriji(int id)
        {
            var dostavaHraneP31ATigriciContext = _context.Hrana.Include(h => h.Restoran).Include(h => h.Tip).Where(h => h.TipId == id);
            return View(await dostavaHraneP31ATigriciContext.ToListAsync());
        }
        public async Task<IActionResult> TopHrana()
        {
            var dostavaHraneP31ATigriciContext = _context.Hrana.Include(h => h.Restoran).Include(h => h.Tip).OrderByDescending(p => p.Glasovi);
            return View(await dostavaHraneP31ATigriciContext.ToListAsync());
        }

        // GET: Hranas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hrana = await _context.Hrana
                .Include(h => h.Restoran)
                .Include(h => h.Tip)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hrana == null)
            {
                return NotFound();
            }

            return View(hrana);
        }

        // GET: Hranas/Create
        public IActionResult Create()
        {
            ViewData["RestoranId"] = new SelectList(_context.Restoran, "Id", "Adresa");
            ViewData["TipId"] = new SelectList(_context.Tip, "Id", "Naziv");
            return View();
        }

        // POST: Hranas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Naziv,RestoranId,TipId,Slika")] Hrana hrana)
        {
            if (ModelState.IsValid)
            {
                _context.Add(hrana);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RestoranId"] = new SelectList(_context.Restoran, "Id", "Adresa", hrana.RestoranId);
            ViewData["TipId"] = new SelectList(_context.Tip, "Id", "Naziv", hrana.TipId);
            return View(hrana);
        }

        // GET: Hranas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hrana = await _context.Hrana.FindAsync(id);
            if (hrana == null)
            {
                return NotFound();
            }
            ViewData["RestoranId"] = new SelectList(_context.Restoran, "Id", "Adresa", hrana.RestoranId);
            ViewData["TipId"] = new SelectList(_context.Tip, "Id", "Naziv", hrana.TipId);
            return View(hrana);
        }

        // POST: Hranas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Naziv,RestoranId,TipId,Slika")] Hrana hrana)
        {
            if (id != hrana.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(hrana);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HranaExists(hrana.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RestoranId"] = new SelectList(_context.Restoran, "Id", "Adresa", hrana.RestoranId);
            ViewData["TipId"] = new SelectList(_context.Tip, "Id", "Naziv", hrana.TipId);
            return View(hrana);
        }

        // GET: Hranas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var hrana = await _context.Hrana
                .Include(h => h.Restoran)
                .Include(h => h.Tip)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (hrana == null)
            {
                return NotFound();
            }

            return View(hrana);
        }
        public IActionResult Narudzba(int id)
        {
            // Budući da spremamo listu ovo je prihvatljivo rješenje:
            List<int> narudzbe = new List<int>();
            narudzbe.Add(id);
            string serijalizirana_lista = JsonConvert.SerializeObject(narudzbe);

            // FINALNO rješenje za upis u Session varijablu Posudbe:
            string narudzbe_string = HttpContext.Session.GetString("Narudzba");
            if (narudzbe_string == null)
            {
                narudzbe = new List<int>();
            }
            else
            {
                narudzbe = JsonConvert.DeserializeObject<List<int>>(narudzbe_string);
            }
            if (!narudzbe.Contains(id))
            {
                narudzbe.Add(id);
            }
            var temp = JsonConvert.SerializeObject(narudzbe);
            HttpContext.Session.SetString("Narudzba", temp);

            // Dohvat hrane u kosarici
            var hrana = _context.Hrana
                .Include(h => h.Restoran)
                .Include(h => h.Tip)
                .Where(item => narudzbe.Contains(item.Id));
            return View(hrana.ToList());
        }
        public IActionResult DeleteIzKosarice(int id)
        {
            List<int> narudzbe = null;
            string narudzbe_string = HttpContext.Session.GetString("Narudzba");
            if (narudzbe_string == null)
            {
                narudzbe = new List<int>();
            }
            else
            {
                narudzbe = JsonConvert.DeserializeObject<List<int>>(narudzbe_string);
            }
            if (narudzbe.Contains(id))
            {
                narudzbe.Remove(id);
                var hran=_context.Hrana.Where(item => item.Id==id);
                foreach (var item in hran)
                {
                    item.Kolicina = 1;
                }
                _context.SaveChanges();
            }
            var temp = JsonConvert.SerializeObject(narudzbe);
            HttpContext.Session.SetString("Narudzba", temp);

            // Dohvat hrane u kosarici
            var hrana = _context.Hrana.Where(item => narudzbe.Contains(item.Id));

            return View("Narudzba", hrana.ToList());
        }
        public async Task<IActionResult> PotvrdiNarudzbu()
        {
            string narudzbe_string = HttpContext.Session.GetString("Narudzba");
            List<int> narudzbe = new List<int>();
            if (narudzbe_string != null)
            {

prog_ing_DostavaHrane/prog_ing_DostavaHrane/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Naruči.hr</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Naruči.hr</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Početna</a></li>
                    <li><a asp-area="" asp-controller="Hranas" asp-action="Index">Naruči hranu</a></li>
                    <li><a asp-area="" asp-controller="Hranas" asp-action="Narudzba">Košarica</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        <img class="imgbanner" src="~/images/common-banner.jpg" alt="BannerHome" />
        @RenderBody()
        <hr />
        <br />
        <footer>
            <div style="text-align:center;margin-bottom:100px">
                <img style="display:inline;margin-right:50px" src="~/images/logo1.png" alt="logo1" />
                <img style="display:inline;margin-right:50px" src="~/images/logo2.png" alt="logo2" />
                <img style="display:inline;margin-right:50px" src="~/images/logo3.png" alt="logo3" />
                <img style="display:inline;margin-right:50px" src="~/images/logo4.png" alt="logo4" />
                <img style="display:inline;margin-right:50px" src="~/images/logo5.png" alt="logo5" />
            </div>
            <br />
            <p style="text-align:center">&copy; 2019 - prog_ing_DostavaHrane - Web aplikacija napravljena za potrebe kolegija Programsko inženjerstvo i upravljanje projektima<br />Studentska grupa P31A - Tim Tigrići</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>